### ISSUE TITLE
SCION simulation not working due to faulty scion-control-service

### ISSUE THREAD

**Issue by amdfxlucas** [seed-labs/seed-emulator#170]
Symptoms:
- scion endhosts in different ASes are unable to 'scion ping' each other -> Error fetching paths
 log files of control service reveal that beacon dissemination failed and thus no paths were discovered

Steps-to-reproduce:
 - start slightly modified bandwidth-test-example( same topology ): https://github.com/amdfxlucas/seed-emulator/blob/master/examples/scion/S06-overlay-multicast/overlay-multicast.py
 
Relevant log files:
[scion_control_service_log.txt](https://github.com/seed-labs/seed-emulator/files/13932512/scion_control_service_log.txt)
[docker_compose_of_faulty_seed_sim.txt](https://github.com/seed-labs/seed-emulator/files/13932540/docker_compose_of_faulty_seed_sim.txt)

**Comment by wonkr** [comment]
@lschulz 
Hello, SCION TEAM, 
I think this is a issue from the SCION implementation. 
Could you please check this issue?
Thanks
