### ISSUE TITLE
Problem with compiled Test cases

### ISSUE THREAD

**Issue by Bruol** [seed-labs/seed-emulator#225]
The Compiled test cases are currently failing, because the naming of `A01-simple-peering` was not updated to `A01-simple-as`. Also the `A02-transit-as` was updated which in turn breaks test cases `A04-visualization` and `A05-components`

I suggest the following fix: 

```python 
  "A00-simple-as": (["simple-as.py"] , ["output"]),
   "A01-transit-as" : (["old-transit-as.py"], ["output", "base-component.bin"]),
```

instead of 

```python
  "A00-simple-peering": (["simple-peering.py"] , ["output"]),
  "A01-transit-as" : (["transit-as.py"], ["output", "base-component.bin"]),
```

in https://github.com/seed-labs/seed-emulator/blob/master/test/compile-test/compile-test.py

**Comment by wonkr** [comment]
We are reorganizing the examples so it causes this issue. The updated version is already in the `development` branch. 
We will revise the compile-test.py as well once we finished to update the example folders. Thanks.
