### ISSUE TITLE
Issue with Example B00-mini-internet

### ISSUE THREAD

**Issue by aramrami** [seed-labs/seed-emulator#40]
When I choose to build the example B00-mini-internet the following command is Ok:

python3 examples/B00-mini-internet/mini-internet.py 

A change to client dir and run dcbuild. I got this error:

Step 6/13 : RUN npm install
 ---> Running in a7256a4a8cb0

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN container-manager-client@0.0.1 No repository field.

npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/acorn/-/acorn-8.0.4.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

$ cat package-lock.json 
{
  "name": "container-manager-client",
  "version": "0.0.1",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {

How can I solve this issue?

**Comment by magicnat** [comment]
The root of the problem was outlined here:

```
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/acorn/-/acorn-8.0.4.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
```

This indicates that `npm` fails to resolve the domain name, `registry.npmjs.org`; can you check and confirm if your system's DNS is configured correctly?

**Comment by aramrami** [comment]
Ok Thanks. I added the correct DNS server in my conf and I will try.

**Comment by wonkr** [comment]
.
