### ISSUE TITLE
A bug in DNS

### ISSUE THREAD

**Issue by kevin-w-du** [seed-labs/seed-emulator#45]
When I create a DNS node, but without adding a zone to it, there is a problem: the `named` server fails to start, because it tries to load the `named.conf.zones` file, but it does not exist. You can easily solve this problem by creating an empty `names.conf.zones` file if no zone is added to this DNS node.

I create such an empty node for the purpose of labs, because I want students to add zones to the nameservers.

**Comment by wonkr** [comment]
https://github.com/wonkr/seed-emulator/commit/d2351911f98d250e30e6f362d5beda84d983f6d3
