### ISSUE TITLE
Zsh and terminal title

### ISSUE THREAD

**Issue by kevin-w-du** [seed-labs/seed-emulator#48]
Once I am inside a container, I would like to set a customized terminal title. Currently, zsh sets the one using `root@<id>`, which is not that useful. I had to run "`NOPRECMD=1 zsh`" to get a new shell, and then type `set_title XYZ` to change the title. Can we add `NOPRECMD=1` to the `/root/.bashrc` when we start zsh, so we don't need to run this command. I am not sure whether this could cause any issue though.

**Comment by kevin-w-du** [comment]
I just read some of the comments in the .zshrc file. It seems it is better to put `NOPRECMD=1` in the /root/.zshrc.pre file. I like this approach better, as we may need to add more customization later. We can use both `.zshrc.pre` and `.zshrc.local`.  

Let's also add `alias st=set_title` to `.zshrc.local`, so it is easier to change the title.

**Comment by magicnat** [comment]
This is completed in the last commit to the `development` branch.

**Comment by kevin-w-du** [comment]
Tested. It is great. Close the issue.
